// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpmiHaduU-jPR2zBlFiS3uZAByWy5IiiE',
    appId: '1:941459768830:web:b170ec68cfa99231f4acaf',
    messagingSenderId: '941459768830',
    projectId: 'champ-7b072',
    authDomain: 'champ-7b072.firebaseapp.com',
    databaseURL:
        'https://champ-7b072-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'champ-7b072.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPVq0zew4SKjckNxaJFYP22zZVYvgE_xg',
    appId: '1:941459768830:android:1bb77256e590f17cf4acaf',
    messagingSenderId: '941459768830',
    projectId: 'champ-7b072',
    databaseURL:
        'https://champ-7b072-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'champ-7b072.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZjbSEh8Prh0GZrEmJsdkCDZkub1heIY8',
    appId: '1:941459768830:ios:3ab1d4a201f5847ef4acaf',
    messagingSenderId: '941459768830',
    projectId: 'champ-7b072',
    databaseURL:
        'https://champ-7b072-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'champ-7b072.firebasestorage.app',
    iosClientId:
        '941459768830-beo3j8rlidoq8iqo036bo19llquff6al.apps.googleusercontent.com',
    iosBundleId: 'com.example.ludotitan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZjbSEh8Prh0GZrEmJsdkCDZkub1heIY8',
    appId: '1:941459768830:ios:3ab1d4a201f5847ef4acaf',
    messagingSenderId: '941459768830',
    projectId: 'champ-7b072',
    databaseURL:
        'https://champ-7b072-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'champ-7b072.firebasestorage.app',
    iosClientId:
        '941459768830-beo3j8rlidoq8iqo036bo19llquff6al.apps.googleusercontent.com',
    iosBundleId: 'com.example.ludotitan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpmiHaduU-jPR2zBlFiS3uZAByWy5IiiE',
    appId: '1:941459768830:web:99a75daf8e1b922bf4acaf',
    messagingSenderId: '941459768830',
    projectId: 'champ-7b072',
    authDomain: 'champ-7b072.firebaseapp.com',
    databaseURL:
        'https://champ-7b072-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'champ-7b072.firebasestorage.app',
  );
}
